@host=https://localhost:7201

Post {{host}}/auth/register
Content-Type: application/json

{
    "firstName" : "David",
    "lastName" : "Aramis",
    "email" : "daoe@outlook.de",
    "password" : "doho@1990"
}

###